Feat/classificacao
RafaelPA13/Challange_Web_Dev pull request #1
Opened 2024-05-28 18:55 UTC by RafaelPA13

O que foi adicionado:

- Customização da tabela de corredores
- Funcionalidade de mapeamento da lista de pilotos
- Funcionalidade de filtragem de pilotos

2024-05-30 14:34 UTC, mtsdnz requested changes

2024-05-30 14:34 UTC, mtsdnz commented on css/classificacao.css
> +}
Esses resets de margens não são necessários aqui, pois já temos no style.css, mesma coisa para font-family.

2024-05-30 14:34 UTC, mtsdnz commented on css/classificacao.css
> +:root {
Existe alguns erros de formatação nesse documento, reformate ele e envie novamente

2024-05-30 14:34 UTC, mtsdnz commented on css/classificacao.css
> +    --cor-branca: #F2F2F2;
Variaveis no CSS tem o proposito de facilitar a mudança de cor caso seja necessária. Se usarmos o nome da cor no nome da variavel, ela perde o sentido, pois caso a gente precise mudar a cor, teriamos que também mudar o nome da váriavel. 

Eu recomendo você renomear essas cores para nomes mais significativos, como "title-color", "title-primary-color", "background-primary", etc.

2024-05-30 14:34 UTC, mtsdnz commented on css/classificacao.css
> +    --fonte: 'Noto Sans', sans-serif;
Esse variavel não é necessária pois já está definida no styles.css

2024-05-30 14:34 UTC, mtsdnz commented on css/classificacao.css
> +    }
Crie uma classe base para as equipes, e seta o border-left:
```css
.team-border {
    border-left: 10px solid;
}
```

Depois para cada equipe você pode alterar apenas a cor dela:
```css
.porsche {
    border-left-color: var(--cor-porsche);
}
```

dessa forma não precisamos repetir o mesmo código varias vezes

2024-05-30 14:34 UTC, mtsdnz commented on css/styles.css
> -
Qual motivo de ter removido essas regras daqui?

2024-05-30 14:34 UTC, mtsdnz commented on css/classificacao.css
> +thead {
Você está setando as regras globalmente aqui, o que significa que qualquer outra tabela que a gente adicionar na página vai seguir essas mesmas regras, o ideal seria criar uma classe mãe para a tabela e colocar as regras dentro dela.

2024-05-30 14:34 UTC, mtsdnz commented on js/classificacao.js
> +
Ao invés de comparar usando ==, use `includes`, dessa forma a busca não precisa ser EXATA:
```javascript
const dados = pilotos.filter((piloto) => {
    return piloto.nome.includes(corredor);
  });
```

2024-05-30 14:34 UTC, mtsdnz commented on js/classificacao.js
> +  const tbody = document.getElementById("tbody");
Use um nome mais descritivo na tabela, como tabela-pilotos
Usar `tbody` é uma má pratica, pois é o mesmo nome do elemento e pode causar confusão

2024-05-30 14:34 UTC, mtsdnz commented on views/classificacao.html
> +        <tbody id="tbody"></tbody>
Altera o id para algo mais significativo, como "pilotos"

2024-05-31 17:58 UTC, RafaelPA13 commented on css/styles.css
> -
Fiz uma classe que formata todos os títulos, a classe .titulos no arquivo styles.css

2024-05-31 18:21 UTC, mtsdnz commented on css/styles.css
> -
Ela formata apenas os h1, e mesmo assim requer que você dê wrapper em uma class titulo, oq é anti pattern, eu recomendo voltar com o antigo

2024-05-31 19:33 UTC, mtsdnz requested changes

2024-05-31 19:33 UTC, mtsdnz commented on css/classificacao.css
> +    height: 824px;
Setar um height fixo e um width variavel faz com que a imagem fique esticada e perca proporçoes de acordo com o tamanho da tela.

Altera para:
```css
width: 100%;
object-fit: fill;
```

2024-05-31 19:33 UTC, mtsdnz commented on css/classificacao.css
> +            }
Como as fotos possuem dimensoes diferentes, algumas fotos estão ficando achatadas. 
Ao invés de setar height e width fixo, coloca apenas max-height:

```css
max-height: 75px;
```

2024-05-31 19:45 UTC, mtsdnz approved these changes

2024-05-31 19:46 UTC, merged